# Generated by Django 4.2.5 on 2023-10-06 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0004_doctors_doctor_extract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_status', models.IntegerField(default=0)),
                ('consultation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('consultation_descriptionm', models.TextField(null=True)),
                ('acreted_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('consultation_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='doctors.doctors')),
                ('consultation_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
