# Generated by Django 4.2.5 on 2023-10-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='consultation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
