# Generated by Django 4.2.5 on 2023-10-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='acreted_date',
            new_name='creted_date',
        ),
    ]
