# Generated by Django 4.2.5 on 2023-09-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialtys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialty',
            old_name='created_date',
            new_name='acreted_date',
        ),
        migrations.AlterField(
            model_name='specialty',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
