# Generated by Django 4.2.5 on 2023-09-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doctor_image',
            field=models.ImageField(default='images/usuario.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doctor_image_name',
            field=models.CharField(default='usuario.png', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
