# Generated by Django 4.2.5 on 2023-10-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctors_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doctor_extract',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
